name: Lighthouse Tests
on:
  push

jobs:

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lighthouse CI Action  
        env:
          PR_NUMBER: ${{ github.event.number }}
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: ./.github/lighthouserc.yml
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true
          urls: |
            https://deploy-preview-${PR_NUMBER}--mesheryio-preview.netlify.app