name: Lighthouse Tests
on:
  push

jobs:

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lighthouse CI Action
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: ./github/workflows/lighthouserc.yml
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true
          urls: |
            ${{ github.event.inputs.deployPrimeUrl }}
            ${{ steps.urls.outputs.urls }}