name: Lighthouse Tests
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Wait for the Netlify Preview
        # https://github.com/JakePartusch/wait-for-netlify-action
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'meshery'
      
      - name: Lighthouse CI Action
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: ./.github/lighthouserc.yml
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true
          urls: |
            ${{ steps.netlify.outputs.url }}